### ISSUE TITLE
Problem with read-more on singular post

### ISSUE THREAD

**Issue by willybahuaud** [uncatcrea/wp-appkit#106]
Content after  is stripped on singular post. I think it's because in _wp-appkit/lib/components/components-utils.php_, the content you get using `get_the_content()` is already filtered, maybe you should use `$post->post_content` instead ?

**Comment by mleroi** [comment]
In fact, get_the_content() relies on a "global $more" to truncate or not truncate the post content when it contains a "more" tag. 
In the native WP screen loading context, this global $more is set to 1 if is_single() or is_page(). 
So, in our WP-AppKit web service context we had to force this global $more to 1 manually so that get_the_content() does not truncate the content... 

Thanks Willy for the feedback! :)
