### ISSUE TITLE
launch.js error : App could not synchronize with website.

### ISSUE THREAD

**Issue by spwebguy** [uncatcrea/wp-appkit#115]
Hi,

New to this plugin. I'm trying to create a new theme. I've got all my files ready in the right theme folder and managed to display the layout.html content but the (content of) **menu.html won't show up**. 

All my tags are there, I'm calling the menu correctly, but it's not showing.

My console says:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.js:1:0

Options retrieved from local storage. Object { options: Object } app-utils.js:11:4

Addons dynamic data retrieved from local storage. Array [  ] app-utils.js:11:4

App error event [synchro:wrong-answer] Wrong "synchronization" web service answer Object { type: "ws-data", where: "app::syncWebService", message: "Wrong "synchronization" web service…", data: Object } app-utils.js:11:4

launch.js error : App could not synchronize with website. app-utils.js:11:4
```

That last line is pretty clear to me. I wonder what I did wrong. Now I'm not an expert but I'm using a VPN here for connecting (China...). Could this be why it's not working? 

I pretty much understand how everything else works, I'm just stuck with this error and can't go further. Any help would be appreciated! Thanks in advance.

G—

**Comment by spwebguy** [comment]
OK.

It seems that it's because I didn't have any component yet. I didn't know you needed to have at least one for the app to call the template parts. Actually this component isn't even attached to the menu, but without it the templates aren't called.

Maybe (not sure haha) this can help others, if they ever get stuck at the very step of building their app. 

This plugin is promising, keep up the amazing work. This is the future.

**Comment by mleroi** [comment]
Hi,

Thanks for using WP-AppKit and for your feedback!

Yes, in the current version, an app must have components (because an app with no component has no content) to be able to run well. But following your feedback we may change the way we handle that for future versions. We just created an issue about this : https://github.com/uncatcrea/wp-appkit/issues/116 :)

You noticed that apps can have components that are not added to the menu.
Components are app's content, and all app's content is not necessarily referenced in the app's menu.
For example you may want to display a component's content in some place of your layout.html or in a custom page of your app. To do so, you can retrieve the content of components that are not in the menu by using TemplateTags.getComponent( component_slug ) in your theme's functions.js (for example) : http://uncategorized-creations.com/wp-appkit/doc/#1847-getcomponent .

We wish you happy app coding, 
for any other questions about WP-AppKit usage you can use our support at support@uncategorized-creations.com.

**Comment by spwebguy** [comment]
Just checked the new issue, totally agrees, even though I was kind of dumb... of course you need component and of course not all of them are going to show in the menu. Sorry for that.

So far I'm having a lot of fun with it. I'll keep reporting if I see anything worth creating an issue here (should mostly be beginner stuff though).

I appreciate the fast answer and how you take the time to help, keep up the great work.

Gia
