### ISSUE TITLE
send forms

### ISSUE THREAD

**Issue by kinti** [uncatcrea/wp-appkit#122]
Hi, 

for example, to use a some plugin to send forms, 
the action is something like: /wp-appkit-api/project/MWE0N2Y0NzNlasdfY2VhMTFiMDJlNzZkMjEyZjdmMWUzNzQ3MmI2NTg3MTNiYmIzNTA1NGIzOTMwNzBkZg=%3D%2Fsynchronization%2F#wpcf7-f3177-o1

how can arrage this, or, how can use forms to send data?
thanks,

**Comment by blupu** [comment]
In hybrid apps, you have to use Ajax to send forms. Here's an example on how to do that: http://samcroft.co.uk/2012/posting-data-from-a-phonegap-app-to-a-server-using-jquery/. Please see the Codex for specificities regarding Ajax in WordPress (codex https://codex.wordpress.org/AJAX_in_Plugins). Also, you should use our our "custom query" webservice/api when communicating from wpak apps because they allow security and to link with app (custom) components.

_Please don't hesitate to ask questions on Stack Overflow as we usually don't do support on Github._
