### ISSUE TITLE
Get more posts in lists is not working

### ISSUE THREAD

**Issue by levybee** [uncatcrea/wp-appkit#124]
Hi, thank you for the great App. I have a few issues however. I have been trying to get more posts to load on the archive.html template with no success. I managed to add the 'load more posts' button and the code inside functions.js by following your documentation but when the button is clicked nothing happens.  Also I tried simple things like just adding a link(button) in the archive template  the adding a handler in the functions.js like: 

          $( '#my-button-name' ).on('click', function(e) {
			 e.preventDefault();
			 
			 console.log('My #my-button-name clicked!');
		    
		} );

Also tried to add that code in the archive template where I have set the link(button) but it does not work. console.log does not give me any result. So if that does not work I don't expect the 'Get more posts' to work. Or maybe I am doing it wrong?  Thanks.

**Comment by blupu** [comment]
Hi, reading your code, I see that you're not using event delegation when binding an event.

```JavaScript
$( '#app-layout' ).on('click', ''#my-button-name'', function(e) {
         e.preventDefault();
         console.log('My #my-button-name clicked!');
} );
```

**Why using event delegation?**
You have to remember that elements may not exist (yet) when you want to bind events to them. In you example, the archive list doesn't exist until you access... a list. So your binding fails because the element (the button) doesn't exist yet. The trick is to bind your event to a permanent element (#app-layout) and let the event bubbles to the element when and if it exists. Fortunatly, jQuery lets you do that easily as shown in the example above.

**Comment by levybee** [comment]
Yup, that worked. Thanks.
