### ISSUE TITLE
Microsoft Project Westminster Support?

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#138]
Hey guys,

Got this through to my inbox today from Microsoft: http://blogs.windows.com/buildingapps/2015/07/06/project-westminster-in-a-nutshell/?WT.mc_id=18275-Dev-bznl-nov-su-ns-2

Looks fairly interesting, especially the tile and offline support, could be a really nice addition to WPAppKit; especially as it'll also target W10 phones as well as W10 desktops, laptops and tablets.

**Comment by lpointet** [comment]
Hi,

We are using Cordova/PhoneGap to build cross-platform apps. For now, we're only supporting iOS and Android platforms since they represent the huge majority of installed ones. We could choose to support Windows platform in the future as well, but as PhoneGap is able to do this bridge, we'll most probably use it.

I'm then closing this issue as wontfix.
