### ISSUE TITLE
Check If We're In Default Screen

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#16]
Would be very useful to be able to check that we're displaying the default screen in functions.js.

I propose to use `current_screen.is_default_screen` for that (?).

**Comment by lpointet** [comment]
@mleroi As discussed and following your comment here (https://github.com/uncatcrea/wp-appkit/commit/5c36fb58f6b478f03ed7e3c9b982878d3915c5ab#commitcomment-14269931), I reverted the addition of an attribute.
Also, I added the ability to pass a screen_data object to the template tag, so that it's not only about current screen, but any screen with current by default.

**Comment by mleroi** [comment]
@lpointet Cool! seems perfect to me :) I just merged it to development
