### ISSUE TITLE
Default to single for page appears to be broken

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#18]
- Pick or create a theme with a single.html but no page.html
- Add a page component (with no sub-pages) in the WordPress admin panel
- Add the component to the navigation
- Compile the app (iOS or Android)
- Launch the app and access the page

x **Page content doesn't show up**

**Expected result:** page content shows up as app should default on the single.html template.

**Comment by blupu** [comment]
@mleroi I believe you've said that it is now working during one of the weekly meetings. Am I right?

**Comment by mleroi** [comment]
Re-tested : problem still there :/
I have to look into it.

**Comment by blupu** [comment]
@mleroi Did you find time to test it on device?

**Comment by mleroi** [comment]
It still fails on device (iOS and android) even if ok in browser.
This one is really tricky and I have no real clue what's causing it, still have to investigate it further...
So this have to be postponed to 0.5 I think.

**Comment by mleroi** [comment]
Fixed with d0f9b6a.
On mobile devices (and not in browsers) require(['text!template']) pass through success callback even if "template" file does not exist :(
To solve this I used the fact that in case the template does not exist the success callback receives an empty string (instead of the template HTML content if the template file exists).
