### ISSUE TITLE
Back action broken for pages

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-appkit#221]
* Insert a page (with no subpages) in the menu
* Navigate to the page (clicking on the menu item) from a post list
* _Page displays_
* Tap physical Android back button
* **Back action doesn't work. Page still displays instead of going back to the post list**

**Comment by mleroi** [comment]
This was due to what's explained here : https://github.com/uncatcrea/wp-appkit/commit/ba3481b343ab8c2896e5249b0b1bdb4086b3f43f#diff-b682a455d3e3be6c4e02dc9797778211R63

And we now have a factorized way of building screen fragments : new function CoreApp.getScreenFragment() : https://github.com/uncatcrea/wp-appkit/commit/ba3481b343ab8c2896e5249b0b1bdb4086b3f43f#diff-95a3c04ea0142ff1385680255da1d96aR267

**Comment by blupu** [comment]
Confirmed. It works now.
