### ISSUE TITLE
HTTP Error 505

### ISSUE THREAD

**Issue by Malome13** [uncatcrea/wp-appkit#232]
I installed WP-appkit and activated it, when I try to add application it gives me a HTTP error 500, says website unable to handle this request, how do I resolve this error?
NB: I am currently running the latest wordpress 4.5.2

**Comment by mleroi** [comment]
Hi and thanks for using WP-AppKit,
We never had this kind of error at app creation before.
Can you please write to our support using the contact form on our website (http://uncategorized-creations.com/contact/) so that we can find a solution to your problem?
In the meantime if you have a way to access your PHP error logs and/or activate WP_DEBUG=true in your wp-config.php, it could help to know more about what's causing the error.
