### ISSUE TITLE
Problems Installing Plugin

### ISSUE THREAD

**Issue by Malome13** [uncatcrea/wp-appkit#233]
Hi, I am having problems with installation of wp-appkit. At first it installed but when I tried adding applications it gave me a error 500, then I ran WP_DEBUG and no errors were found. I resorted to reinstalling it again and I got "The plugin does not have a valid header"...Please help.

**Comment by lpointet** [comment]
Hi,
Thanks again for testing WP-AppKit. These issues (here on github) are not meant to be our support tool, so please contact us via our website (http://uncategorized-creations.com/contact/) so that we can properly help you.
For example, we'll need to know how you installed our plugin (e.g. by providing us the files you downloaded).
I'm closing the 2 issues you created.

**Comment by mleroi** [comment]
Hi @Malome13 we just fixed on development branch what may have caused the "The plugin does not have a valid header" problem: there was an empty line before the plugin header. This problem was only on development branch of WP-AppKit, so if you were using this branch your problem may be fixed now, if you want to try again.

**Comment by Malome13** [comment]
Yes I would like to try again, can I get the link to download of the fixed plugin? or should I just use the one on github? 

    On Thursday, June 16, 2016 9:07 PM, mleroi <notifications@github.com> wrote:
 

 Hi @Malome13 we just fixed on development branch what may have caused the "The plugin does not have a valid header" problem: there was an empty line before the plugin header. This problem was only on development branch of WP-AppKit, so if you were using this branch your problem may be fixed now, if you want to try again.—

**Comment by mleroi** [comment]
Yes the last version of development branch can be found here:
https://github.com/uncatcrea/wp-appkit/archive/development.zip

**Comment by Malome13** [comment]
Thank You, will giveit a try and let you know how it goes 

    On Thursday, June 16, 2016 9:35 PM, mleroi <notifications@github.com> wrote:
 

 Yes the last version of development branch can be found here:
https://github.com/uncatcrea/wp-appkit/archive/development.zip—
