### ISSUE TITLE
Trying to log an user by its WP ID

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#235]
Is there a way to "auto log" an user knowing his WP ID?

Thank you

**Comment by mleroi** [comment]
Hi, 
If I understand you well, you would like to log a user from your app knowing only its numeric user ID.

WP-AppKit authentication is based on user login(or email) + password, so it won't be possible out of the box to log a user in only from its ID.
 
However, there may be some workarounds:
- If you really have no way to use user login (or email) we can tell you how to retrieve user's login from user's ID, then pass this login to the app and use it for authentication in the app.
- if you're really ok to allow users to log in without providing their password, it should be doable by hooking on WP native "_check_password_" filter: with this hook you can force user connection without password.

**Comment by eskaigualker** [comment]
Hi (and thank you for your help).
I will allow the users to log with their Facebook account. What I have planned is to create an user in WP using the FB email address, or get the wp user if this email is already in use.
So, at this point I will have all the user information in wp (email, ID, username, etc). With that I'd like to "auto log" this user and continue working.

Thank you!

**Comment by mleroi** [comment]
Hi,
I think I'll need more info about what exactly is your authentication process **on app side**: user opens the app, then how do you know its ID or email in the app? via Facebook login on app side? via login form? Then what does the authentication allows the user to do on app side: access restricted posts or screens, display user info, ...?

To continue this discussion, could you please use our support form here: http://uncategorized-creations.com/contact/ so that we can go into more details about your specific situation? (We try to keep Github issues for _issues_ only).
Thanks!
