### ISSUE TITLE
Push notification for new posts

### ISSUE THREAD

**Issue by hakansenturk** [uncatcrea/wp-appkit#243]
I would like to inform my users with push notifications for the new posts on word press. How can I do that within wpappkit? Or is there another service for this?

**Comment by blupu** [comment]
WP-AppKit exports Cordova apps. These apps **can** implement push notifications. We use PushWoosh in our projects but there's many solutions out there (including doing it by yourself). To have an automatic sending when publishing a post, you'll have to develop a WordPress (which uses the PushWoosh API for example). You'll also have to add to your app's theme a landing screen for your push notifications.

**Comment by jagovea** [comment]
Hello, amazing work as always.

In my Android compilation, I can not see the notification icon. I already tried several methods and it still does not work. Can you help me please?

`<img src="https://analysin.com/wp-content/uploads/2019/04/WhatsApp-Image-2019-04-09-at-8.04.26-AM.jpeg">`

Thank you.

**Comment by mleroi** [comment]
Hi @jagovea, 
Can you please write to us at support[at]uncategorized-creations.com so that we can try to find what's wrong for you? 
This icon issue is not really related to the first subject of this issue ("Push notification for new posts").
We will then open another issue in github if it can help others.
Thanks, regards
