### ISSUE TITLE
Remote connection to website failed

### ISSUE THREAD

**Issue by eskaigualker** [uncatcrea/wp-appkit#244]
When I run the app with no connection to internet, this error is fired. I thought that the app could run offline. Trying with original q-ios theme.

**Comment by mleroi** [comment]
You have to connect to internet at least once to populate your app with content from your WP site. Then, all downloaded content (corresponding to all your app's components) is available offline.

If you launch your app for the first time with no internet connection, the app can't download any content.

If you already downloaded some content and re-launch the app with no internet connection, the app automatically tries to refresh content from server, which fails, so it displays "Remote connection to website failed", but all previously downloaded content is still available offline.

Note that "auto check and refresh at app launch" can be deactivated by setting the "refresh-at-app-launch" param to false : http://uncategorized-creations.com/wp-appkit/doc/#1588-refresh-at-app-launch

If your need is to embed content directly in app so that it is directly pre-populated with content when you build it, without requiring any internet connexion, it is not possible for now, but it is one of the main features we're thinking about for futur developments.

**Comment by eskaigualker** [comment]
Thinking about this. Even the first time, the app should be able to launch. If there is no connection and no content, then there is no content. But the app skeleton should be available. Could not be this way?

**Comment by blupu** [comment]
Hi, we re-tested this use case (first launch / no connection / non content) and it works (event the UX is poor as our test theme doesn't handle this case).
