### ISSUE TITLE
Malformed config.xml in PhoneGap Build when fetching the repository for first time

### ISSUE THREAD

**Issue by HammyHavoc** [uncatcrea/wp-appkit#248]
Not had this problem before, was wondering if you could take a look at my config.xml: https://github.com/HammyHavoc/Lost-Found-for-Android

Probably something silly. Will be sure to give credit on the app announcement post on the L&F website. :- )

**Comment by lpointet** [comment]
Hi,
Glad to see you're ready to go live!
Your problem is probably because of the non-escaped "&" from your description. It should be replaced by its xml entity, something like "&amp;". 
Tell me of it's work. I also keep this issue open since we surely should take care of this kind of escaping in a future release. 
Cheers.

**Comment by HammyHavoc** [comment]
Hey Lionel! Perfect fix, thank you for that, will let you know when the post goes up. :- )

**Comment by HammyHavoc** [comment]
Here we go: https://www.lostandfound.mu/lost-found-android-app-now-available :- )
