### ISSUE TITLE
Overall preview problem

### ISSUE THREAD

**Issue by dfuzion2014** [uncatcrea/wp-appkit#261]
Hi, I use WP 4.6 + WPAppkit 0.6. With all themes I get a javascript error on console
`Uncaught SyntaxError: Unexpected end of input         -----     functions.js?wpak_app_id=test2-ios&bust=1472288524696:714 `
Header (refresh and menu), bottom button in an article page aren't working.
I checked on Safari, Chrome and Firefox. Same problem.

Did anyone get this problem?
Thanks for your feedback.
Jérôme

**Comment by blupu** [comment]
Generally this generic error message is raised by a missing ; closing ] or }... What theme do you use? If you've used one of the Q, did you modify it?
It seems also that problems can happen with JSON http headers. See this for more explanations: http://stackoverflow.com/questions/3594923/chrome-uncaught-syntaxerror-unexpected-end-of-input

**Comment by dfuzion2014** [comment]
I use Q for iOS and didn't modified it. You can see it here

`http://www.d-fuzion.com/wp-content/plugins/wp-appkit/app/index.html?wpak_app_id=test2-ios#component-blog`

On firefox I have more informataions on console

`L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert. index.html
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.js:1:0
SyntaxError: missing } after function body functions.js:714:4`

I added the missing } but it generate another error...

**Comment by blupu** [comment]
If I read correctly the Firefox error message, it seems you have a charset encoding problem rather than a code problem.

I've looked at your http headers returned by the server and it is true that there's not encoding specified. (I also saw that you use Varnish.)

Let's try a first possible solution:
 * locate and edit the file _head.html_ in your app's theme.
 * Add `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`. You may also try `<meta charset="UTF-8">`

**Comment by dfuzion2014** [comment]
I added both meta to header.html and problems are the same.
I use Q for iOS 1.0.2. is that the last version ?

**Comment by lpointet** [comment]
Hi,
It seems the last line of functions.js is missing in your installation (see here: https://github.com/uncatcrea/q-ios/blob/master/js/functions.js#L716).
To avoid the errors, you should add this line at the end of your file (`});`).

Plus, our themes are meant to run on mobile devices using touch screen, meaning that they listen to _touch_ events: you then need to activate these events in your browser while previewing your app.

The encoding message usually isn't a real problem since browsers will guess it automatically.
Tell me if it helps.

**Comment by dfuzion2014** [comment]
Thanks for your help guys !
Encoding isn't a problem for sure. But function.js has one. I checked and compared my file and the one from Github and they are exactly the same. The end isn't shown in console because the script stops before. I checked every braces and I really can't figure what the problem is. 
I also checked this preview on my iphone and nothing works...
Any idea ??

**Comment by lpointet** [comment]
Thing is, if you directly go to http://www.d-fuzion.com/wp-content/plugins/wp-appkit/app/themes/q-ios/js/functions.js?wpak_app_id=test2-ios&bust=1472296312578 you can see the last line isn't there. I checked and you are right, your _real_ file contains this missing line.
So I guess there might be a problem with the cached version within Varnish: do you have the ability to flush it, or maybe deactivate it temporarily on all wp-appkit URLs?

**Comment by dfuzion2014** [comment]
You're right that's a Varnish problem... I desactivated in htaccess (as proposed by Gandi) and purge it but nothing changed. And I need it for the web site performances.

I saw that there's a directive for node.js :
`function (request, response) {
    response.setHeader('Cache-Control', 'max-age=1');
}`
Do you think it could work on your framework? And were should I put it ?
I also can do it in php.

I just checked wp-appkit on another host and all is working like a charm :)

**Comment by lpointet** [comment]
OK, let's give it a try. You can modify the `WpakThemes::exit_send_theme_file` function, see here: https://github.com/uncatcrea/wp-appkit/blob/master/wp-appkit/lib/themes/themes.php#L423
Just add the following line:
`header( 'Cache-Control: max-age=1' );`
This will only affect theme files, but `functions.js` is one of them, so we can quickly see if it's working.
As this is a core file, we'll have to figure out another, long-term solution for this kind of case, to avoid having to modify it each time you update the plugin ;).

**Comment by dfuzion2014** [comment]
I afraid it's not working... I also tried meta cache-control index.html from theme and from plugin and same result...

**Comment by lpointet** [comment]
Could you try creating another app on the same server, with the same theme, and see if it's better?

**Comment by dfuzion2014** [comment]
Same problem....

**Comment by mleroi** [comment]
Hi, 
So we've made some tests with your app and it seems that all theme's Javascript files are missing their last characters: for example:
- http://www.d-fuzion.com/wp-content/plugins/wp-appkit/app/themes/q-ios/js/functions.js?wpak_app_id=test2-ios&bust=1472557093405 > missing });
- http://www.d-fuzion.com/wp-content/plugins/wp-appkit/app/themes/q-ios/js/moment.min.js?wpak_app_id=test2-ios&bust=1472296312579 > missing "});"

So there seems to be a problem somewhere with your specific server configuration that truncates some of the served files (meaning the files are ok on your server, but truncated after being served), but we can't manage to figure out what it is exactly.

Maybe it is Varnish or could also be a problem with PHP's readfile() function:
As you may have noticed, when previewing in browser, the theme's JS files we see in browser at `wp-content/plugins/wp-appkit/app/themes/q-ios/js/` are not really in this directory but in `wp-content/themes-wp-appkit/app/themes/q-ios/js/` directory: they are in fact *served by PHP using the readfile() function* so that they virtually appear as being in the theme.
So it's unlikely but maybe there could be a problem with the readfile() function on your install, that truncates the end of files. If ok with you we can send you a short PHP script that would allow to test readfile() on its own ?

Also, could you please try to export your app (Phonegap Build Export button). This will download a zip to your computer with your app sources. Then unzip it and check the files in `themes/q-ios/js`. Can you tell us if they're ok? If so, it would confirm that files are ok on server side, but something is going wrong when serving them.

**Comment by dfuzion2014** [comment]
Hi,

Ok to test readfile() with your script. You can send it to me and tell me what to do. We could maybe go in private chat or do it by email ?
Each time I export a phonegap build, I get a zip file unable to uncompress. In fact myBuild.zip becomes myBuild.zip.cpgz (i'm on osx). I tried wp-appkit on other hosting and zip files are ok. Weird...

**Comment by mleroi** [comment]
Yes, can you write to our support through our website here: http://uncategorized-creations.com/contact-us/#question and we'll send you a test file by email.

**Comment by mleroi** [comment]
Solution to this issue has been found on private support: some plugin or theme on the WP install was echoing some non visible characters (certainly UTF8 BOM) that made WPAK theme and zip files downloads crash.
Cleaning output buffer before sending theme and zip files solved that.
