### ISSUE TITLE
app preview fails after export

### ISSUE THREAD

**Issue by roholdt** [uncatcrea/wp-appkit#286]
After exporting an app, the preview in wp-admin no longer works.

The error message (and yes, I did check I was connected, and I checked/resaved permalinks): 

WP AppKit error : config.js not found.
Please check that : 
- you are connected to your WordPress back office,
- WordPress permalinks are activated

Considering the config file is not even generated until export, and everything was working fine before, I don't see how it could be necessary for preview. But I tried simply copying the config-file from the exported folder, and putting it in the wp-appkit-master/wp-appkit/app folder to see if it helped. This at least made the error messages somewhat more informative. The app is trying to load this:  

vendor/../themes/AFM-theme/head.html

… which of course it can't find, because there is no such folder. The preview is acting as though it were an exported app, rather than looking for the files in themes-wp-appkit. 

I tried changing the app's theme to one of the defaults, an I also tried making a new app, to see if there was anything specifically wrong with the one I'm working on, but I can no longer preview apps at all.

What can I do to fix this?

**Comment by roholdt** [comment]
Ok, the problem appears to have been solved. Apparently, the exported files need to be copied into plugins/wp-appkit-master/wp-appkit/app after export. I assume this is supposed to happen automatically, and failed for some reason on our wp-install.

**Comment by roholdt** [comment]
Actually, strike that. There is something weird going on here, and I would very much like to know what. Uploading the files to the aforementioned folder made the preview work again, more or less, but it is now effectively previewing the exported app files, not the theme I am working on.

**Comment by lpointet** [comment]
Hi,
If I understand well, you managed to preview your app correctly, then exported it, and after that, without changing anything, you cannot preview it anymore. Is that right?

First thing to know is that you don't need to put the exported app anywhere on your website's server: it's only useful to _build the app_ on PhoneGap Build.
Secondly, WP-AppKit uses some rewrite rules in order for the preview to work properly. That's why the error message asks you to check if your permalinks are activated. It means you cannot preview an app if your permalink structure is the default one (`?p=id`). Plus, that's why you can see the preview is trying to access files that don't really exist: the rewrite rules should get the correct files from `themes-wp-appkit` folder (or from the plugin source code itself).

Could you then:
1. remove all exported files you put inside your WordPress installation (config, theme files, etc.)
2. confirm you're using a specific permalink structure (ex: `%postname%`)
3. turn on the _debug mode_ on your app
4. click "View config.js" link and check what is returned
5. click "Show Me Web Service Data" and check what is returned
6. preview your app with the developer console open and see if there are some errors showing up in there

For more reactivity (and privacy), you can email us to support@uncategorized-creations.com so that we can follow up on this.

**Comment by lpointet** [comment]
As discussed through our support channel, you are running a Multisite install on an Nginx web server, you can follow the steps [from our tutorial about this specific configuration](https://uncategorized-creations.com/2437/how-to-install-wp-appkit-with-nginx/), it should help you configure your web server and make WP-AppKit work.

**Comment by roholdt** [comment]
Not here to reopen the issue, simply for clarity, in case it helps someone else: we never actually solved this. 

I don't know anything about servers, but I was told by our backenders that the tutorial's  instructions for multisite/ngix did not work (not all that surprising, as it is stated in the tutorial that the code is untested for this scenario). We ended up rebuilding the app in another framework.

Probably this is a fringe case, and won't affect that many users. But in our situation at least, wp-appkit turned out not to be the right fit.
