### ISSUE TITLE
Application bug continues

### ISSUE THREAD

**Issue by multiversonews** [uncatcrea/wp-appkit#320]
Even after uninstalling the appkit it still left a bug in wordpress.
How to remove this?
![sem titulo](https://user-images.githubusercontent.com/26308997/27504122-bdcff76e-5852-11e7-8dac-880d37b445d9.png)

**Comment by blupu** [comment]
Confirmed. If _App Editor_ role has been activated, it remains when the plugin is deactivated (tested with 1.0.2).

@multiversonews we are going to fix that in the next version. Thank you. In the meantime:

- Reinstall/Reactivate WP-AppKit
- Go to the _WP-AppKit_ > _Settings_ panel
- Uncheck the _Activate a "WP-AppKit App Editor" role..._
- Click the _Save settings_ button
- Check that the role doesn't exist anymore in _Users_ panel
- Deactivate/Uninstall WP-AppKit

**Comment by multiversonews** [comment]
I followed your instructions but still has an error, a function still exists and users are created automatically. Look
![app](https://user-images.githubusercontent.com/26308997/27509018-03aaed70-58c1-11e7-8461-2a43ca4f0d30.png)
![45](https://user-images.githubusercontent.com/26308997/27509028-2a26fd2c-58c1-11e7-8274-cad9e287628b.png)

**Comment by mleroi** [comment]
Hi @multiversonews, I just pushed on our development branch a fix that removes the custom "WP-AppKit App Editor" role on plugin deactivation. Thank you for helping us fixing that bug.

But I see you also have another role "App Subscriber" (which WP-AppKit does not create) and strange user creations. Could you please tell us what other plugins you are using, so that we can see if one of them conflicts with WP-AppKit role creation? thanks.
