### ISSUE TITLE
Refresh current page and screen scroll

### ISSUE THREAD

**Issue by Ices-Eyes** [uncatcrea/wp-appkit#326]
Hi all, I have a couple of question to ask :P
I have implemented a new post comment function that allow for sending comment without authentication (in the blog i'm devoloping the app for the users just insert a nick and an email to post comments). To ddo this I have written a php page that acept the comment form data and insert it in the db. But in this way I'm not able to get in the same call the updated list of comments, hence I tried to update the current screen when the comment has been posted. I tried with App.reloadCurrentScreen() in function.js. But what I obtain is that the "previous" fragment (hence the single post page from which I reach the comment page with the form - the comments.html has the list of comments and then the form) is readded to the history, and then cannot navigate front or back anymore... I tried also to apply the solution of issue #262 / #264 here on github, but nothing changed... Is there a way to completle reload the page and let the others thing still work?

Also, on the same comments.html page, every comment has a button on right that should allow for reply to it. I would like to move to the bottom of the screen when one tap the button, but not able to handle that. Tried something like window.scrollTo( 0, $("#new-comment").position().top  where #new-comment is the div containig the form, nothing happen with this code...

Thanks for your support if possible :)

**Comment by mleroi** [comment]
Hi!

Here's a function that allows to reload the current comments screen without messing with app history:
```
/**
 * When on a comments screen, reloads the comments for the current post and
 * re-renders the view to display new comments.
 */
function update_current_comment_screen( cb_ok, cb_error ) {

	//Retrieve post id corresponding to the current comments screen:
	var current_screen_info = App.getCurrentScreenObject();
	var post_id = current_screen_info.post.id;

	//Flush comments cache for the post:
	CoreApp.comments.remove( post_id );

	//Reload post comments from server:
	CoreApp.getPostComments(
		post_id,
		function ( comments, post, item_global ) {
			//New comments loaded successfully				

			//Update current view's comments with new comments
			var comments_view = RegionManager.getCurrentView();
			comments_view.comments = comments;

			//Rerender screen:
			App.rerenderCurrentScreen();

			cb_ok( comments, post );
		},
		function ( error ) {
			cb_error( error );
		}
	);
}
```
Note that you have to require 2 core modules CoreApp and RegionManager for this to work: add this to the first line of functions.js:
`define( [..., 'core/app', 'core/region-manager',...], function( ..., CoreApp, RegionManager, ... ) { ` 

And here's a usage example that will call the function when clicking a "#reload-comment" link on the comments screen: this reloads the comments list screen with no modification of app history:
```
$("#app-layout").on("click","#reload-comments", function(e){
	e.preventDefault();

	//Maybe add a spinner or something here while loading new comments from server

	update_current_comment_screen(
		function() {
			//Success
			//Hide spinner if any and if it is not already removed when the view re-rendered
		},
		function( error ) {
			//An error occured
			//Hide spinner if any
		}
	);

});
```

I hope this helps. 
If it still does not work as expected for you, can you please write directly to our support email support[at]uncategorized-creations.com so that we can help you about this specific need? If something useful for others comes out, we'll post it back here.
You can also post your scroll question on support email too so that we can dispatch it better among the answering team.
Thanks

**Comment by Ices-Eyes** [comment]
Thanks a lot! I will try that this evening, and eventually will report here if it works, or will go through the support mail, but I believe it will works! Thanks again :)

**Comment by Ices-Eyes** [comment]
Ok, so it works perfectly!!! Thanks a lot!!!
I also find a way to scroll the page. On the button touchend event I used $(this).closest('.appscreen').scrollTop($('mydiv').position().top!!! ;)

**Comment by mleroi** [comment]
Great to hear that it worked well for you!
I'll add this comment screen refresh function to the core/theme-app module in next version of WP-AppKit so that it can be called natively from themes.
