### ISSUE TITLE
Fresh install: config.js and config.xml not found

### ISSUE THREAD

**Issue by stevenkellow** [uncatcrea/wp-appkit#329]
Just installed the plugin and was trying to preview a very plain app setup, but when testing Phonegap settings the config.xml file couldn't be found and when previewing it gave me: "WP AppKit error : config.js not found."

**Comment by MrAliyev** [comment]
The same here. 

WP AppKit error : config.js not found.
Please check that : 
- you are connected to your WordPress back office,
- WordPress permalinks are activated

**Comment by mleroi** [comment]
Hi, there are different causes that can lead to this issue.

Can you please contact our support at support[at]uncategorized-creations.com and specify in your email if:
- your server is running Apache / Nginx / Other... 
- you use a cache plugin or a Varnish like solution ?

You can also make the following test to see if the problem comes from WordPress rewrite rules:
- go to your "Settings > Permalinks" back office screen and click "Save changes" to be sure that your rewrite rules are flushed
- maybe check again if you're preview is working after that
- if not, click on the "Show me webservice data" button (in your app edition panel) and tell us what you have: an error or webservice data displaying?

Thanks

**Comment by MrAliyev** [comment]
- go to your "Settings > Permalinks" back office screen and click "Save changes" to be sure that your rewrite rules are flushed
_Doesn't help_

- click on the "Show me webservice data" button (in your app edition panel) and tell us what you have: an error or webservice data displaying?
_displays json data_

I just installed and activated another plugin and WP-AppKit started working fine :100: 
When I deactivate the plugin, WP-AppKit preview stops working :-1:

**Comment by mleroi** [comment]
I'm closing this issue as we discussed those problems by support email. They were due to specific server configs: a not yet fully identified problem with theme install for stevenkellow, and Windows server config for MrAliyev.
You can contact the support again at support[at]uncategorized-creations.com for any other question.
