### ISSUE TITLE
Extracted PhoneGap zip file invalid

### ISSUE THREAD

**Issue by JMcM** [uncatcrea/wp-appkit#377]
I am running WP 5.0.3 and WP-AppKit 1.5.3, when I export my PhoneGap build, the zip file downloads fine, but when I try to extract it, it says the zip file is invalid. Any ideas?

**Comment by mleroi** [comment]
Hi,
This issue is often due to something (plugin or theme unwanted output) messing up with the zip download done via PHP from Back Office.
To be sure, can you try to manually download the export zip that can be found in wp-content/uploads/wpak-export/[export-type]-export-[app-slug].zip ?
You should be able to access it at https://[your-site]/wp-content/uploads/wpak-export/[export-type]-export-[app-slug].zip

Does this zip work for you?

**Comment by JMcM** [comment]
That did the trick, thank you!
